'use client';
import React,{useState} from 'react';
import {ArrowRight,Search,CheckCircle2} from 'lucide-react';
import {request,resourceTitle,money,resourceLabels} from '../../lib/workspace';
export default function DemandPanel({data,onSaved}:{data:any;onSaved:()=>Promise<void>}){
 const [selected,setSelected]=useState<any>(null),[matches,setMatches]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function match(r:any){setSelected(r);setError('');setBusy(true);try{setMatches((await request(`/matches/${r.id}`)).matches);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function offer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await request('/offers','POST',{listingId:f.get('listingId'),requirementId:selected.id,quantity:selected.quantityNeeded||1,price:Number(f.get('price'))});setNotice('Offer sent to the demand owner.');setSelected(null);await onSaved();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const available=data.requirements.filter((r:any)=>!r._count?.offers);
 return <section className="ks-panel" style={{marginBottom:24}}><div className="ks-section-heading"><div><p className="ks-eyebrow">DEMAND BOARD</p><h2>Connect supply with demand</h2></div><Search size={23}/></div>{error&&<p className="ks-alert error">{error}</p>}{notice&&<p className="ks-alert"><CheckCircle2 size={16}/>{notice}</p>}{available.length?available.slice(0,12).map((r:any)=><div className="ks-row" key={r.id}><div className="ks-grow"><strong>{resourceTitle(r)} · {resourceLabels[r.resourceType]}</strong><small>{r.party.name} · {r.district} · {r.quantityNeeded||1} units · Budget {money(r.budget)}/unit</small></div><button disabled={busy} className="ks-button secondary" onClick={()=>match(r)}>Find matches <ArrowRight size={14}/></button></div>):<p className="ks-subtitle">No open demand yet. Buyers can publish requirements from their workspace.</p>}{selected&&<div className="ks-note"><h3>Matches for {resourceTitle(selected)}</h3><p>Ranked by the resource matching strategy: quantity, quality, proximity, price and credibility where applicable.</p>{matches.length?matches.slice(0,5).map(m=><div className="ks-row" key={m.listingId}><div className="ks-grow"><strong>{m.title}</strong><small>{m.partyName} · {m.district} · {money(m.price)}</small></div><b>{Math.round(m.score)}% fit</b></div>):<p>No compatible open listings were found.</p>}{selected.partyId!==data.party.id&&<form className="ks-form" onSubmit={offer}><label>Your listing<select name="listingId" required><option value="">Select your compatible listing</option>{data.listings.filter((l:any)=>l.partyId===data.party.id&&l.status==='OPEN'&&l.resourceType===selected.resourceType).map((l:any)=><option key={l.id} value={l.id}>{resourceTitle(l)} · {money(l.price)}</option>)}</select></label><label>Offer price per unit<input name="price" type="number" min="0.01" step="0.01" required defaultValue={selected.budget||20}/></label><button disabled={busy} className="ks-button">Respond with an offer</button></form>}</div>}</section>;
}
